<a href="https://colab.research.google.com/github/Ganeshpy3/chatbot/blob/main/chatbot.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import keras 
from keras.layers import Dense
from keras.models import Sequential
import pandas as pd
import numpy as np
import json
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import CountVectorizer

In [4]:
file=open("/content/sample_data/intent.json")

In [5]:
data=json.load(file)

In [6]:
print(data["intends"])

[{'tags': 'welcome', 'patterns': ['hi', 'hello', 'hey', 'hi', 'hey there'], 'response': ['hello', 'hey whats up', 'hi']}, {'tags': 'thankyou', 'patterns': ['bye', 'see you', 'thanks bye'], 'response': ['bye take care', 'see you :)']}, {'tags': 'intro', 'patterns': ['what is your name', 'who are you', 'what are you'], 'response': ['iam chitti a chatbot', 'Artificial chatbot']}, {'tags': 'question', 'patterns': ['how are you', 'how you', 'are you fine'], 'response': ['iam fine', ':)fine,how are you ?']}, {'tags': 'found', 'patterns': ['who created you', 'when you born', 'how you created'], 'response': ['Iam an Artificial chatbot Founded by Ganesh']}]


In [7]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [8]:
ps=PorterStemmer()

In [225]:
intenddict={}
for intend in data["intends"]:
  intenddict[intend["tags"]]=[i for i in intend["response"]]


In [226]:
intenddict

{'found': ['Iam an Artificial chatbot Founded by Ganesh'],
 'intro': ['iam chitti a chatbot', 'Artificial chatbot'],
 'question': ['iam fine', ':)fine,how are you ?'],
 'thankyou': ['bye take care', 'see you :)'],
 'welcome': ['hello', 'hey whats up', 'hi']}

In [9]:
allwords=[]
intent=[]
text=[]
for intend in data["intends"]:
  # print(intend["tags"])
  inte=intend["tags"]
  for p in intend["patterns"]:
    intent.append(inte)
    li=[]
    p=word_tokenize(p)
    for val in p:
       valu=ps.stem(val.lower())
       li.append(valu)
       allwords.append(valu)
    text.append(" ".join(li))

In [10]:
intent

['welcome',
 'welcome',
 'welcome',
 'welcome',
 'welcome',
 'thankyou',
 'thankyou',
 'thankyou',
 'intro',
 'intro',
 'intro',
 'question',
 'question',
 'question',
 'found',
 'found',
 'found']

In [11]:
df=pd.DataFrame({"Text":text,"Intent":intent})

In [12]:
le=LabelEncoder()

In [13]:
Y=le.fit_transform(df["Intent"])

In [14]:
Y

array([4, 4, 4, 4, 4, 3, 3, 3, 1, 1, 1, 2, 2, 2, 0, 0, 0])

In [15]:
allwords=set(allwords)

In [148]:
def bag_of_words(words,allwords=allwords):
  # words=word_tokenize(words)

  data=np.zeros(len(allwords))
  for idx,value in enumerate(allwords):
    if value in words:
      data[idx]=1

  return data




In [158]:
Xbag=[]
for sentence in df["Text"]:
  Xbag.append(bag_of_words(sentence))

Xbag

[array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0.]),
 array([0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.]),
 array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.]),
 array([0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.]),
 array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        1., 0.]),
 array([0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.]),
 array([1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0.,
        0., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0.,
        0., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 

In [155]:
X=pd.DataFrame(Xbag,columns=allwords)
X

is   hi  hey  born  bye  name  when  ...  you  your  what  who  fine  see  how
0   0.0  1.0  0.0   0.0  0.0   0.0   0.0  ...  0.0   0.0   0.0  0.0   0.0  0.0  0.0
1   0.0  0.0  0.0   0.0  0.0   0.0   0.0  ...  0.0   0.0   0.0  0.0   0.0  0.0  0.0
2   0.0  0.0  1.0   0.0  0.0   0.0   0.0  ...  0.0   0.0   0.0  0.0   0.0  0.0  0.0
3   0.0  1.0  0.0   0.0  0.0   0.0   0.0  ...  0.0   0.0   0.0  0.0   0.0  0.0  0.0
4   0.0  0.0  1.0   0.0  0.0   0.0   0.0  ...  0.0   0.0   0.0  0.0   0.0  0.0  0.0
5   0.0  0.0  0.0   0.0  1.0   0.0   0.0  ...  0.0   0.0   0.0  0.0   0.0  0.0  0.0
6   0.0  0.0  0.0   0.0  0.0   0.0   0.0  ...  1.0   0.0   0.0  0.0   0.0  1.0  0.0
7   0.0  0.0  0.0   0.0  1.0   0.0   0.0  ...  0.0   0.0   0.0  0.0   0.0  0.0  0.0
8   1.0  0.0  0.0   0.0  0.0   1.0   0.0  ...  1.0   1.0   1.0  0.0   0.0  0.0  0.0
9   0.0  0.0  0.0   0.0  0.0   0.0   0.0  ...  1.0   0.0   0.0  1.0   0.0  0.0  0.0
10  0.0  0.0  0.0   0.0  0.0   0.0   0.0  ...  1.0   0.0   1.0  0.0   0.0  0.0  0.0
11  0.0  0.0  0.0   0.0  0.0   0.0   0.0  ...  1.0   0.0   0.0  0.0   0.0  0.0  1.0
12  0.0  0.0  0.0   0.0  0.0   0.0   0.0  ...  1.0   0.0   0.0  0.0   0.0  0.0  1.0
13  0.0  0.0  0.0   0.0  0.0   0.0   0.0  ...  1.0   0.0   0.0  0.0   1.0  0.0  0.0
14  0.0  0.0  0.0   0.0  0.0   0.0   0.0  ...  1.0   0.0   0.0  1.0   0.0  0.0  0.0
15  0.0  0.0  0.0   1.0  0.0   0.0   1.0  ...  1.0   0.0   0.0  0.0   0.0  0.0  0.0
16  0.0  0.0  0.0   0.0  0.0   0.0   0.0  ...  1.0   0.0   0.0  0.0   0.0  0.0  1.0

[17 rows x 19 columns]

In [19]:
X.shape

(17, 19)

In [131]:
model=Sequential()
model.add(Dense(units=1000,activation="relu",kernel_initializer='he_uniform',input_dim=19))
model.add(Dense(units=500,activation="relu",kernel_initializer="he_uniform"))
model.add(Dense(units=5,activation="softmax"))

In [132]:
model.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_11 (Dense)             (None, 1000)              20000     
_________________________________________________________________
dense_12 (Dense)             (None, 500)               500500    
_________________________________________________________________
dense_13 (Dense)             (None, 5)                 2505      
Total params: 523,005
Trainable params: 523,005
Non-trainable params: 0
_________________________________________________________________


In [133]:
model.compile(loss="sparse_categorical_crossentropy",metrics=["accuracy"])

In [134]:
classifier=model.fit(X,Y,epochs=20)

Epoch 1/20
1/1 [==============================] - 1s 603ms/step - loss: 1.5482 - accuracy: 0.4118
Epoch 2/20
1/1 [==============================] - 0s 5ms/step - loss: 0.6484 - accuracy: 0.7647
Epoch 3/20
1/1 [==============================] - 0s 6ms/step - loss: 0.4377 - accuracy: 0.8235
Epoch 4/20
1/1 [==============================] - 0s 6ms/step - loss: 0.1732 - accuracy: 0.9412
Epoch 5/20
1/1 [==============================] - 0s 5ms/step - loss: 0.0363 - accuracy: 1.0000
Epoch 6/20
1/1 [==============================] - 0s 5ms/step - loss: 0.0281 - accuracy: 1.0000
Epoch 7/20
1/1 [==============================] - 0s 8ms/step - loss: 0.0231 - accuracy: 1.0000
Epoch 8/20
1/1 [==============================] - 0s 8ms/step - loss: 0.0196 - accuracy: 1.0000
Epoch 9/20
1/1 [==============================] - 0s 6ms/step - loss: 0.0169 - accuracy: 1.0000
Epoch 10/20
1/1 [==============================] - 0s 6ms/step - loss: 0.0147 - accuracy: 1.0000
Epoch 11/20
1/1 [====================

In [135]:
a=bag_of_words("hey buddy",allwords)

In [136]:
b=pd.DataFrame([a])

In [209]:
def predict(inp):
  if len(model.predict(inp)[model.predict(inp)>0.5])>0:
    return le.inverse_transform([np.argmax(model.predict(inp))])



In [210]:
model_json = model.to_json()
with open("model.json", "w") as json_file:
    json_file.write(model_json)
model.save_weights("model.h5")

In [217]:
def command(data):
  p=word_tokenize(data)
  li=[]
  for valu2 in p:
    value=ps.stem(valu2.lower())
    li.append(value)
  inp=bag_of_words(" ".join(li))
  output=predict(pd.DataFrame([inp]))
  return output

  


In [218]:
command("hey")

array(['welcome'], dtype=object)

In [228]:
import random

In [234]:
def chat():
  while True:
    inp=input("You:")
    if inp=="exit":
      return False
    else:
      print("Chitti: ",random.choice(intenddict[command(inp)[0]]))

In [236]:
chat()

You:hey
Chitti:  hi
You:how are you
Chitti:  :)fine,how are you ?
You:how you
Chitti:  :)fine,how are you ?
You:hii
Chitti:  hello
You:who created u
Chitti:  Iam an Artificial chatbot Founded by Ganesh
You:who are you
Chitti:  Artificial chatbot
You:bye
Chitti:  see you :)
You:exit


False